### ISSUE TITLE
Statistics fail due to inconsistent tagging

### ISSUE THREAD

**Issue by vy** [vy/reactor-pubsub#9]
Publishing metrics from `MeterRegistry` to Prometheus fails with the following error message:

```
Prometheus requires that all meters with the same name have the same
set of tag keys. There is already an existing meter named
'pubsub_client_seconds' containing tag keys [operation, projectName, result,
subscriptionName, type]. The meter you are attempting to register has keys
[operation, projectName, result, rootCauseClassName, subscriptionName,
type].
```

**Comment by vy** [comment]
@wvl, I will appreciate some review and feedback here. Given [the metrics we expose](https://github.com/vy/reactor-pubsub#how-can-i-enable-metrics), how shall we structure them in a way that avoids the conflict restricted by Prometheus?

**Comment by wleese** [comment]
So I'm surprised to see this. My initial reaction would be that Prometheus has no such limitation on metrics. A metric can have multiple (tag) dimensions. I can imagine if multiple dimensions were used within a histogram or set - indeed that would be weird behaviour for a client.

I see you're using micrometer timers and counters. At the risk of sounding arrogant - I wouldn't be surprised if this was a misunderstanding by the micrometer devs.

**Comment by wleese** [comment]
Some interesting discussion in the issue https://github.com/prometheus/client_java/issues/52, especially https://github.com/prometheus/client_java/issues/52#issuecomment-69164568.

If the java client library has some consistency with the golang one, then perhaps having different metadata for the various possible metric dimensions will allow reuse of the metric name.
https://godoc.org/github.com/prometheus/client_golang/prometheus#Desc

In my opinion, having the same tag set for a metric coming from an application is a convenience because it enables a quick understanding of all possible ways to query said metric. There are cases however, where I can imagine that keep multiple tag dimensions for a single metric name within a single process overrides the benefit of slightly easier querying.

I'd suggest that if there are multiple dimensions which cannot concisely be described and categorized within the practical limitations of metric name, to indeed reuse the same metric name if possible (if the library allows it :)).

**Comment by vy** [comment]
Thanks so much for the exhaustive investigation @wleese. Fixing the misalignment between Micrometer, Prometheus Micrometer driver in Java, and Prometheus itself is quite a challenge to tackle. Due to development resource constraints and as a workaround for current users, I will rather just fix my metric names and tags.

In its current form, `PubsubClient` exposes the following metrics: 

<table>
    <thead>
        <tr>
            <th rowspan="2">Name</th>
            <th colspan="7">Tags</th>
        </tr>
        <tr>
            <th>type</th>
            <th>operation</th>
            <th>projectName</th>
            <th>subscriptionName</th>
            <th>topicName</th>
            <th>result</th>
            <th>rootCauseClassName</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="4">pubsub.client</td>
            <td>timer</td>
            <td>publish</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>{succes,failure}</td>
            <td>?</td>
        </tr>
        <tr>
            <td>timer</td>
            <td>{pull,ack}</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>{succes,failure}</td>
            <td>?</td>
        </tr>
        <tr>
            <td>counter</td>
            <td>publish</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>counter</td>
            <td>{pull,ack}</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
    </tbody>
</table>

This creates tag discrepancies between both types `timer`-vs-`counter` and operations `publish`-vs-`{pull,ack}` metrics. I propose to restructure the metrics as follows:

<table>
    <thead>
        <tr>
            <th rowspan="2">Name</th>
            <th colspan="6">Tags</th>
        </tr>
        <tr>
            <th>type</th>
            <th>projectName</th>
            <th>subscriptionName</th>
            <th>topicName</th>
            <th>result</th>
            <th>rootCauseClassName</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>pubsub.client.{pull,ack}</td>
            <td>{timer,counter}</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>{succes,failure}</td>
            <td>?</td>
        </tr>
        <tr>
            <td>pubsub.client.publish</td>
            <td>{timer,counter}</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>{succes,failure}</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

This structure will employ the very same set of tags for each distinct metric name and hence address the constraint imposed by `PrometheusMeterRegistry`.
